#
# Copyright 2022- IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache-2.0
#

language: c++
dist: focal

services:
- docker
env:
  global:
  - DOCKER_CACHE_DIR=$HOME/travis/cache
  matrix:
  - DOCKER_BUILD_TARGET=ubuntu20.04 CMAKE_BUILD_TYPE=Release
  - DOCKER_BUILD_TARGET=ubuntu20.04 CMAKE_BUILD_TYPE=Debug
  - DOCKER_BUILD_TARGET=ubuntu22.04 CMAKE_BUILD_TYPE=Release
  - DOCKER_BUILD_TARGET=ubuntu22.04 CMAKE_BUILD_TYPE=Debug
  - DOCKER_BUILD_TARGET=debian11.5 CMAKE_BUILD_TYPE=Release
  - DOCKER_BUILD_TARGET=debian11.5 CMAKE_BUILD_TYPE=Debug
notifications:
  email:
    on_success: never
    on_failure: always
before_install:
- ".travis/build-or-cache-grpc.sh"
script:
- ".travis/build-geds.sh"
cache:
  directories:
  - "$DOCKER_CACHE_DIR"
  timeout: 1000

deploy:
  provider: releases
  file_glob: true
  file: travis_artifacts/*
  skip_cleanup: true
  api_key:
    secure: ohB3a2pK6hA/a+g2Z2iciSnwsiJKeDhC34SXdAaVPZQfxCTgZ4aar+rwNE+l7acC/yJUlPc+dhE7YZpdKdQR3C8fR0j5tTdprW9mjqsI4+qMM0mGv8y44XOx47Wgf8MJYMbBIaVW+gP0lvoTQ2HKci0B3Esdul0M3Z743jHNxK0lAkXvA3wUr+fJ+0ODeIHcXTL1dBa/OPiu41QQ27FMsmm6g8nYppmbk15g0v73v4tWnKjD5PRiQYCX0NdFkJ18L9k+1nGzWY7hJAGpgzY9oKqasKaSod0eay8Ti4W0azkKej8+okFOnh6vKZCVzUyN40X7aE45yFj+qEyv2/u1707vyoLRH+UwdJPIJ9do6OlwQ2GCPRTrLSpA6NNgPW/P63dZQf+84gdIAWMQWdmqMvJxF4fObqKTeAmcHisNK2nXmVAhfAx+iEm1+y66dla9zsyulSaGDdopgACVmlLOI1hGI9y7hN+jJaL58IhyUUoK2cQVzwRjZnSX06DChn4ZVQU0y+o99ViMNozo1EC8/L7WKuJRQdd4GO3rXD+NgAVZCLRHGg8tNOvvgfOXWALE6fMHcjtce4uzyneTpvociLxEClx0nUbhJXM+IdCpSIgfbIL0/ndXs+FGDljAhaUKB8pMLzyfZnqwzX52UhKeyZkb0yG3a4L2a7xvKt8XF88=
  on:
    repo: IBM/GEDS
    tags: true
    branch: main
