version: '3.9'
services:
  gedsmds:
    container_name: gedsmds
    image: 'epezhman/gedsmds:latest'
    restart: always
#    logging:
#      driver: journald
    ports:
      - '50001:50001'
#    volumes:
#      - '/home/ubuntu/gedsmds/logs:/gedsmds/logs'
#      - '/home/ubuntu/gedsmds/data:/gedsmds/data'
#      - '/home/ubuntu/gedsmds/configs:/gedsmds/configs'
#    build:
#      context: .
#      dockerfile: gedsmds.dockerfile
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 1s
#        max_attempts: 5
#        window: 10s
