{
 "title": "GEDS Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Namespace", "label": "namespaces", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "GEDS Relocating",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (spark_app_name) (geds__storage_relocated{namespace=\"$Namespace\"})",
     "legendFormat": "{{spark_app_name}} - Storage Relocated"
    },
    {
     "expr": "sum by (spark_app_name) (geds__local_storage_used{namespace=\"$Namespace\"})",
     "legendFormat": "{{spark_app_name}} - Local Storage used"
    }
   ]
  },
  {
   "title": "Aggregate Bandwidth [2m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (spark_app_name) (rate(java_gedsfile__bytes_read_sum{namespace=\"$Namespace\"}[2m]))",
     "legendFormat": "{{spark_app_name}}: GEDS Read"
    },
    {
     "expr": "sum by (spark_app_name) (rate(java_gedsfile__bytes_written_sum{namespace=\"$Namespace\"}[2m]))",
     "legendFormat": "{{spark_app_name}}: GEDS write"
    },
    {
     "expr": "sum by (spark_app_name) (rate(gedsremotefilehandle__bytes_read{namespace=\"$Namespace\"}[2m]))",
     "legendFormat": "{{spark_app_name}}: GEDS Remote FileHandle"
    },
    {
     "expr": "sum by (spark_app_name) (rate(gedss3filehandle__bytes_read{namespace=\"$Namespace\"}[2m]))",
     "legendFormat": "{{spark_app_name}}: GEDS S3 FileHandle"
    },
    {
     "expr": "sum by (spark_app_name) (rate(gedslocalfilehandle__bytes_read{namespace=\"$Namespace\"}[2m]))",
     "legendFormat": "{{spark_app_name}}: GEDS Local FileHandle"
    },
    {
     "expr": "sum by (spark_app_name) (rate(gedscachedfilehandle__bytes_read{namespace=\"$Namespace\"}[2m]))",
     "legendFormat": "{{spark_app_name}}: GEDS Cached File Handle"
    }
   ]
  },
  {
   "title": "GEDS GO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(geds_mds_go_mds_create_objects_total{namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "geds_mds_go_mds_lookup_objects_total{namespace=\"$Namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "geds_mds_go_mds_update_objects_total{namespace=\"$Namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "geds_mds_go_mds_delete_objects_total{namespace=\"$Namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "geds_mds_go_mds_list_objects_total{namespace=\"$Namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "geds_mds_go_mds_pubsub_matching{namespace=\"$Namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "geds_mds_go_mds_pubsub_send_publication{namespace=\"$Namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP Transport Statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (spark_app_name) (geds__tcptransport_recvqueue_length{namespace=\"$Namespace\"})",
     "legendFormat": "{{spark_app_name}}: TCP recv queue length"
    },
    {
     "expr": "sum by (spark_app_name) (geds__tcptransport_sendqueue_length{namespace=\"$Namespace\"})",
     "legendFormat": "{{spark_app_name}}: TCP send queue length"
    }
   ]
  },
  {
   "title": "Aggregated Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "(sum by (spark_app_name) (java_gedsfile__read_sum{namespace=\"$Namespace\"})) /  (sum by (spark_app_name) (java_gedsfile__read_count{namespace=\"$Namespace\"}))",
     "legendFormat": "{{spark_app_name}} - GEDS Read"
    },
    {
     "expr": "(sum by (spark_app_name) (java_gedsfile__write_sum{namespace=\"$Namespace\"})) /  (sum by (spark_app_name) (java_gedsfile__write_count{namespace=\"$Namespace\"}))",
     "legendFormat": "{{spark_app_name}}: GEDS write"
    },
    {
     "expr": "(sum by (spark_app_name) (java_gedsfile__seal_sum{namespace=\"$Namespace\"})) /  (sum by (spark_app_name) (java_gedsfile__seal_count{namespace=\"$Namespace\"}))",
     "legendFormat": "{{spark_app_name}}: GEDS seal"
    },
    {
     "expr": "(sum by (spark_app_name) (java_gedsfile__open_sum{namespace=\"$Namespace\"})) /  (sum by (spark_app_name) (java_gedsfile__open_count{namespace=\"$Namespace\"}))",
     "legendFormat": "{{spark_app_name}}: GEDS open"
    }
   ]
  },
  {
   "title": "File Statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(geds__files_created{namespace=\"$Namespace\"}) by (spark_app_name)",
     "legendFormat": "{{spark_app_name}} - GEDS: Files Created"
    },
    {
     "expr": "sum(gedscachedfilehandle__count{namespace=\"$Namespace\"}) by (spark_app_name)",
     "legendFormat": "{{spark_app_name}}: GEDS Cached File Handles"
    },
    {
     "expr": "sum(gedslocalfilehandle__count{namespace=\"$Namespace\"}) by (spark_app_name)",
     "legendFormat": "{{spark_app_name}}: GEDS Local FileHandles"
    },
    {
     "expr": "sum(gedss3filehandle__count{namespace=\"$Namespace\"}) by (spark_app_name)",
     "legendFormat": "{{spark_app_name}}: GEDS S3 FileHandle"
    },
    {
     "expr": "sum(gedsremotefilehandle__count{namespace=\"$Namespace\"}) by (spark_app_name)",
     "legendFormat": "{{spark_app_name}}: GEDS Remote FileHandles"
    }
   ]
  },
  {
   "title": "I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (spark_app_name) (java_gedsfile__bytes_read_sum{namespace=\"$Namespace\"})",
     "legendFormat": "{{spark_app_name}}: GEDS Read"
    },
    {
     "expr": "sum by (spark_app_name) (java_gedsfile__bytes_written_sum{namespace=\"$Namespace\"})",
     "legendFormat": "{{spark_app_name}}: GEDS write"
    },
    {
     "expr": "sum by (spark_app_name) (gedsremotefilehandle__bytes_read{namespace=\"$Namespace\"})",
     "legendFormat": "{{spark_app_name}}: GEDS Remote FileHandle"
    },
    {
     "expr": "sum by (spark_app_name) (gedss3filehandle__bytes_read{namespace=\"$Namespace\"})",
     "legendFormat": "{{spark_app_name}}: GEDS S3 FileHandle"
    },
    {
     "expr": "sum by (spark_app_name) (gedslocalfilehandle__bytes_read{namespace=\"$Namespace\"})",
     "legendFormat": "{{spark_app_name}}: GEDS Local FileHandle"
    },
    {
     "expr": "sum by (spark_app_name) (gedscachedfilehandle__bytes_read{namespace=\"$Namespace\"})",
     "legendFormat": "{{spark_app_name}}: GEDS Cached File Handle"
    }
   ]
  },
  {
   "title": "Spark I/O Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (spark_app_name) (rate(metrics_executor_totalShuffleRead_bytes_total{namespace=\"$Namespace\"}[2m]))",
     "legendFormat": "{{spark_app_name}} - Shuffle Read"
    },
    {
     "expr": "sum by (spark_app_name) (rate(metrics_executor_totalShuffleWrite_bytes_total{namespace=\"$Namespace\"}[2m]))",
     "legendFormat": "{{spark_app_name}}  - Shuffle Writes"
    }
   ]
  },
  {
   "title": "Spark I/O Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (spark_app_name) (metrics_executor_totalShuffleRead_bytes_total{namespace=\"$Namespace\"})",
     "legendFormat": "{{spark_app_name}} - Shuffle Read"
    },
    {
     "expr": "sum by (spark_app_name) (metrics_executor_totalShuffleWrite_bytes_total{namespace=\"$Namespace\"})",
     "legendFormat": "{{spark_app_name}}  - Shuffle Writes"
    }
   ]
  },
  {
   "title": "Aggregated Container Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (spark_app_name) (rate(container_network_receive_bytes_total{namespace=\"$Namespace\"}[$__rate_interval]))",
     "legendFormat": "{{spark_app_name}} - RX"
    },
    {
     "expr": "- sum by (spark_app_name) (rate(container_network_transmit_bytes_total{namespace=\"$Namespace\"}[$__rate_interval]))",
     "legendFormat": "{{spark_app_name}} - TX"
    }
   ]
  },
  {
   "title": "Operation Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(geds__files_created{namespace=\"$Namespace\"}) by (spark_app_name)",
     "legendFormat": "{{spark_app_name}} - GEDS: Files Created"
    },
    {
     "expr": "sum(geds__files_opened{namespace=\"$Namespace\"}) by (spark_app_name)",
     "legendFormat": "{{spark_app_name}} - GEDS: Files Opened"
    },
    {
     "expr": "sum(java_gedsfile__read_count{namespace=\"$Namespace\"}) by (spark_app_name)",
     "legendFormat": "{{spark_app_name}}: GEDS read"
    },
    {
     "expr": "sum(java_gedsfile__write_count{namespace=\"$Namespace\"}) by (spark_app_name)",
     "legendFormat": "{{spark_app_name}}: GEDS write"
    },
    {
     "expr": "sum(java_gedsfile__seal_count{namespace=\"$Namespace\"}) by (spark_app_name)",
     "legendFormat": "{{spark_app_name}}: GEDS seal"
    }
   ]
  },
  {
   "title": "Network: Packets Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{namespace=\"$Namespace\"}[$__rate_interval])) by (spark_app_name)",
     "legendFormat": "{{spark_app_name}} - RX"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_total{namespace=\"$Namespace\"}[$__rate_interval])) by (spark_app_name)",
     "legendFormat": "{{spark_app_name}} - TX"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (spark_app_name) (container_memory_working_set_bytes{namespace=\"$Namespace\", image !=\"\"})",
     "legendFormat": "{{spark_app_name}} - Working Set Memory"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "CPU Cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$Namespace\", image!=\"\"}[$__rate_interval])) by (spark_app_name) ",
     "legendFormat": "{{spark_app_name}} - Used"
    }
   ]
  }
 ]
}