#
# Copyright 2022- IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache-2.0
#

FROM debian:11.5

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

RUN apt-get clean && apt-get update \
    && apt-get install -y --no-install-recommends \
        openjdk-11-jdk-headless gcc-10 \
        python3.9 python3.9-distutils \
        curl \
    && apt-get clean \
    && curl -o /tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py \
    && python3.9 /tmp/get-pip.py \
    && python3.9 -m pip install numpy

COPY travis_install/geds/ /usr/local/
RUN ls /usr/local

EXPOSE 4380
EXPOSE 4381
EXPOSE 4382
