#
# Copyright 2022- IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache-2.0
#

ARG DOCKER_BUILD_TARGET
ARG GEDS_DOCKER_VERSION

FROM geds_dependencies-${DOCKER_BUILD_TARGET}:${GEDS_DOCKER_VERSION}

ARG GEDS_VERSION
ENV GEDS_VERSION ${GEDS_VERSION}

ARG CMAKE_BUILD_TYPE=Release
ENV CMAKE_BUILD_TYPE ${CMAKE_BUILD_TYPE}

ENV INSTALL_PREFIX /usr/local/opt/geds

ADD . /src/geds
RUN /src/geds/docker/build.sh
