#
# Copyright 2023- IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache-2.0
#

ARG GIT_REVISION
FROM geds-build_ubi8:${GIT_REVISION} as builder

FROM registry.access.redhat.com/ubi8/ubi

RUN yum install -y  \
    curl \
    gcc-toolset-12-runtime \
    openssl-devel \
    python3.11 \
    java-11-openjdk java-11-openjdk-devel

COPY --from=builder /usr/local/opt/geds/ /usr/local/

ENV PATH=/opt/rh/gcc-toolset-12/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    LD_LIBRARY_PATH=/opt/rh/gcc-toolset-12/root/usr/lib64:/opt/rh/gcc-toolset-12/root/usr/lib \
    PKG_CONFIG_PATH=/opt/rh/gcc-toolset-12/root/usr/lib64/pkgconfig

EXPOSE 4380
EXPOSE 4381
EXPOSE 4382
