#
# Copyright 2022- IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

ARG DEFAULT_LOCALE=en_US.UTF-8

RUN apt-get clean apt-get clean && apt-get update && \
    apt-get install -y --no-install-recommends \
        clang \
        git \
        curl wget \
        build-essential ninja-build \
        openjdk-11-jdk \
        python3.9 python3.9-dev python3-distutils \
        gcc-10 g++-10 cpp-10 \
        libcurl4 libcurl4-openssl-dev libssl-dev \
        locales && \
    update-alternatives --install \
        /usr/bin/gcc gcc /usr/bin/gcc-10 100 \
            --slave /usr/bin/g++ g++ /usr/bin/g++-10 \
            --slave /usr/bin/gcov gcov /usr/bin/gcov-10

RUN locale-gen ${DEFAULT_LOCALE}
ENV LC_ALL=${DEFAULT_LOCALE}
ENV LANG=${DEFAULT_LOCALE}
ENV LANGUAGE=${DEFAULT_LOCALE}
