#
# Copyright 2022- IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache-2.0
#

FROM debian:12

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/
ARG DEFAULT_LOCALE=en_US.UTF-8

RUN apt-get clean && apt-get update && \
    apt-get install -y --no-install-recommends \
        clang \
        git \
        curl wget \
        build-essential gcc ninja-build \
        openjdk-17-jdk \
        python3.11 python3.11-dev python3-distutils \
        zlib1g-dev \
        libcurl4 libcurl4-openssl-dev libssl-dev \
        locales

RUN locale-gen ${DEFAULT_LOCALE}
ENV LC_ALL=${DEFAULT_LOCALE}
ENV LANG=${DEFAULT_LOCALE}
ENV LANGUAGE=${DEFAULT_LOCALE}
