#
# Copyright 2022- IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#

ARG GIT_REVISION
ARG DOCKER_BUILD_TARGET
FROM geds_dependencies-${DOCKER_BUILD_TARGET}:$GIT_REVISION

ARG GEDS_VERSION
ENV GEDS_VERSION ${GEDS_VERSION}

ARG CMAKE_BUILD_TYPE=Release
ENV CMAKE_BUILD_TYPE ${CMAKE_BUILD_TYPE}

ENV INSTALL_PREFIX /usr/local/opt/geds

ADD . /src/geds
RUN /src/geds/docker/build.sh
