apiVersion: v1
kind: Pod
metadata:
  generateName: geds-python-read-
spec:
  containers:
  - name: geds-python-read
    image: us.icr.io/zrlio/geds-dev:latest
    command: [ "python3.9", "/usr/local/python/read.py"  ]
    imagePullPolicy: Always
    ports:
    - containerPort: 50003
    env:
    - name: GEDS_METADATASERVER
      value: geds-metadataserver:50001
  imagePullSecrets:
    - name: zrlio
